# Generated by Django 4.0.4 on 2022-05-28 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_rename_caracteristicas_tipohabitacion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 17, 20, 31, 681922, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 17, 20, 31, 684921, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='cod_servicio',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
