# Generated by Django 4.0.4 on 2022-05-31 02:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_alter_checkout_fecha_salida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 2, 46, 23, 57335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='checkout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authApp.checkout'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 2, 46, 23, 60336, tzinfo=utc)),
        ),
    ]
