# Generated by Django 4.0.4 on 2022-06-03 00:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_alter_checkout_fecha_salida_alter_factura_checkout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='numero_dias',
            new_name='numero_noches',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 0, 30, 53, 168746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 0, 30, 53, 174745, tzinfo=utc)),
        ),
    ]
