# Generated by Django 4.0.4 on 2022-06-03 17:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0005_rename_numero_dias_reserva_numero_noches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='fecha_salida',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 17, 6, 3, 881088, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 17, 6, 3, 889090, tzinfo=utc)),
        ),
    ]
